### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by dangus21** [theScottyJam/BuildlessTypeScript#2]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

What is up with the versioning of the project?

**Comment by theScottyJam** [comment]
Just checking - did you see this section in the README?

> What's up with the huge version numbers?
> This project's version numbers can be parsed as follows - If you omit the last two digits of each segment, you will get a TypeScript version number, so a Buildless TypeScript version number of 500.301.304 really means "TypeScript version 5.3.3". The remaining digits are to allow Buildless TypeScript to release semver compatible releases between TypeScript versions. With the 500.301.304 example again, that version number says that 4 patch releases and 1 minor release have come out for this tool since it provided the TypeScript 5.3.3 release. Every time this fork incorporates a new TypeScript version, it will reset the last two digits back to 00.

The weird versioning is just to allow someone to see from the version number what version of TypeScript it is for, but also to allow me to make additional releases whenever I want, all while following semver.

**Comment by theScottyJam** [comment]
Also - didn't realize the issue templates got copied over from the TypeScript repo - I dropped those :p
